name: Docker 标记与构建
description: 一个辅助操作，用于简化生成 Docker 标签和构建镜像的过程
inputs:
  component-name:
    description: 组件或 Docker 镜像的名称（例如:worldserver、authserver)
    type: string
    required: true
  push:
    description: 是否推送镜像
    type: boolean
    required: true
  version:
    description: 用于 Docker 镜像的版本标签
    required: true
    type: string
  dockerfile:
    description: 要使用的 Dockerfile
    required: false
    default: apps/docker/Dockerfile
  registries:
    description: 用逗号分隔的目标 Docker 注册表列表（例如：docker.io,ghcr.io）
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: 解析注册表并生成镜像列表
      id: generate-images
      run: |
        registries=(${{ inputs.registries }})
        component="${{ inputs.component-name }}"
        images=()
        for registry in "${registries[@]}"; do
          images+=("${registry}/${component}")
        done
        echo "images=$(IFS=,; echo "${images[*]}")" >> $GITHUB_ENV

    - name: 获取 Docker 元数据
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.images }}/ac-wotlk-${{ inputs.component-name }}
        tags: |
          type=raw,value=${{ inputs.version }}
          type=ref,event=branch

    - name: 构建并推送
      uses: docker/build-push-action@v5
      with:
        context: ${{ github.workspace }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        target:  ${{ inputs.component-name }}
        build-args: |
          USER_ID=1000
          GROUP_ID=1000
          DOCKER_USER=acore
