name: 艾泽拉斯+机器人构建Docker发布

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-ubuntu:
    name: 拉取构建
    runs-on: ubuntu-latest
    steps:

      - name: 拉取核心代码
        uses: actions/checkout@v4
        with:
          repository: 'liyunfan1223/azerothcore-wotlk'
          ref: 'Playerbot' 

      - name: 拉取当前项目
        uses: actions/checkout@v4
        with:
          path: 'azerothcore-wotlk/acore-docker'

      - name: 拉取Eluna代码
        uses: actions/checkout@v4
        with:
          repository: 'azerothcore/mod-eluna'  
          ref: 'master'
          path: 'azerothcore-wotlk/modules/mod-eluna'
      - name: 拉取playerbots代码
        uses: actions/checkout@v4
        with:
          repository: 'liyunfan1223/mod-playerbots'  
          ref: 'master'
          path: 'azerothcore-wotlk/modules/mod-playerbots'
 
      - name: 登录 Docker Hub 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Get version 
        id: version 
        run: |
          version="$(jq -r '.version' acore.json)"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: 设置 Docker Buildx 环境
        uses: docker/setup-buildx-action@v3

      - name: build worldserver 
        uses: acore-docker/.github/actions/docker-tag-and-build 
        with:
          component-name: worldserver # 指定组件名称
          version: ${{ steps.version.outputs.version }} # 使用之前提取的版本号
          push: true # 如果在主分支运行，则推送镜像

      - name: build authserver # 构建 authserver Docker 镜像
        uses: /acore-docker/.github/actions/docker-tag-and-build
        with:
          component-name: authserver
          version: ${{ steps.version.outputs.version }}
          push: true

      - name: build db-import # 构建 db-import Docker 镜像
        uses: /acore-docker/.github/actions/docker-tag-and-build
        with:
          component-name: db-import
          version: ${{ steps.version.outputs.version }}
          push: true

      - name: build client-data # 构建 client-data Docker 镜像
        uses: /acore-docker/.github/actions/docker-tag-and-build
        with:
          component-name: client-data
          version: ${{ steps.version.outputs.version }}
          push: true

      - name: build tools # 构建 tools Docker 镜像
        uses: /acore-docker/.github/actions/docker-tag-and-build
        with:
          component-name: tools
          version: ${{ steps.version.outputs.version }}
          push: true

      - name: build dev-server # 构建 dev-server Docker 镜像（使用自定义 Dockerfile）
        uses: /acore-docker/.github/actions/docker-tag-and-build
        with:
          component-name: dev-server
          version: ${{ steps.version.outputs.version }}
          push: true


